import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://37.27.17.198:8084/cs/');
  await page.getByRole('link', { name: ' Přihlásit se' }).click();
  await page.getByRole('link', { name: 'Nemáte účet? Vytvořte si jej' }).click();
  await page.getByRole('radio', { name: 'Pan', exact: true }).check();
  await page.getByRole('textbox', { name: 'Jméno' }).click();
  await page.getByRole('textbox', { name: 'Jméno' }).fill('PqhAArIY');
  await page.getByRole('textbox', { name: 'Příjmení' }).click();
  await page.getByRole('textbox', { name: 'Příjmení' }).fill('SdKtwTMl');
  await page.getByRole('textbox', { name: 'E-mail' }).click();
  await page.getByRole('textbox', { name: 'E-mail' }).fill('pqhaariy176055890846889@test.com');
  await page.getByRole('textbox', { name: 'Pole pro heslo' }).click();
  await page.getByRole('textbox', { name: 'Pole pro heslo' }).fill('PQHAARIYqhaariy_pw@test');
  await page.getByRole('progressbar').click();
  await page.getByText('Oslovení Pan Paní Jméno').click();
  await page.getByRole('textbox', { name: 'Datum narození' }).click();
  await page.getByRole('textbox', { name: 'Datum narození' }).fill('01.01.1990');
  await page.getByText(' I agree to the terms and').click();
  await page.getByText('The personal data you provide').click();
  await page.getByRole('button', { name: 'Uložit' }).click();
  await page.getByRole('button', { name: 'favorite_border' }).nth(1).click();
  await page.getByText('My wishlist').click();
  await page.getByText('Produkt přidán').click();
  await page.getByRole('link', { name: 'PqhAArIY SdKtwTMl' }).click();
  await page.getByRole('link', { name: 'favorite My wishlists' }).click();
  await page.getByText('My wishlist (1) share').click();
  await page.getByRole('button', { name: 'Přidat do košíku' }).click();
  await page.getByRole('link', { name: /Pokračovat do pokladny/i }).click();
  await page.getByRole('link', { name: /Pokračovat do pokladny/i }).click();
  await page.getByRole('textbox', { name: 'Alias' }).fill('qwe');
  await page.getByRole('textbox', { name: 'Adresa' }).fill('qwe');
  await page.getByRole('textbox', { name: 'Město / Obec' }).fill('qwe');
  await page.getByLabel('Stát (kraj / oblast)').selectOption('4');
  await page.getByRole('textbox', { name: 'PSČ' }).fill('12000');
  await page.getByRole('button', { name: 'Pokračovat' }).click();
  await page.locator('.row.carrier').click();
  await page.getByRole('button', { name: 'Pokračovat' }).click();
});